### ISSUE TITLE
HTTP Error 400

### ISSUE THREAD

**Issue by Pithikos** [dmotitsk/coursera#11]
This doesn't work atm. Probably the structure of Coursera has changed slightly and since the code hasn't been updated for some years, it doesn't work with the "newer" coursera.

Reproduce:

```
python coursera.py nlp -v -e
```

Output:

```
Traceback (most recent call last):
  File "coursera.py", line 352, in <module>
    main()
  File "coursera.py", line 347, in main
    dl.authenticate()
  File "coursera.py", line 71, in authenticate
    urlencode({'email': EMAIL, 'password': PASSWORD})
  File "/media/manos/SPArmor/Videos/coursera/env/lib/python2.7/site-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/media/manos/SPArmor/Videos/coursera/env/lib/python2.7/site-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 400: Bad Request
```

**Comment by dmotitsk** [comment]
Unfortunately I don't maintain this project any more. If someone is interested in it, I will give the full control over it.
