### ISSUE TITLE
Error in downloading NLP lectures from coursera

### ISSUE THREAD

**Issue by njmccracken** [dmotitsk/coursera#4]
When I run the coursera.py script to download all the NLP lectures:

> > python coursera.py nlp -v -e

it gets an error right after downloading the 4th lecture for nlp/08 "Building a MaxEnt Model:  The Nuts and Bolts".  I believe that the next file is the pptx file for the 5th lecture in nlp/08.  Here is the error when I reran the coursera.py script, which skipped all the already downloaded files:

... (skipped all the earlier skipping messages)
skipping file 'nlp/08 - Week 4 - Discriminative classifiers_ Maximum Entropy classifiers/04 - Building a Maxent Model_ The Nuts and Bolts (8_04).mp4'
Traceback (most recent call last):
  File "dmotitsk-coursera-f9c2bc6/coursera.py", line 297, in <module>
    main()
  File "dmotitsk-coursera-f9c2bc6/coursera.py", line 293, in main
    dl.download()
  File "dmotitsk-coursera-f9c2bc6/coursera.py", line 92, in download
    self.download_part(part_dir, part)
  File "dmotitsk-coursera-f9c2bc6/coursera.py", line 101, in download_part
    row_names[idx].text.strip()), row)
  File "dmotitsk-coursera-f9c2bc6/coursera.py", line 107, in download_row
    self.download_resource(dir_name, name, resource)
  File "dmotitsk-coursera-f9c2bc6/coursera.py", line 113, in download_resource
    ext = self.get_file_ext(url, content_type, res_type)
  File "dmotitsk-coursera-f9c2bc6/coursera.py", line 166, in get_file_ext
    return DEFAULT_EXT[res_type]
KeyError: u'pptx'

**Comment by dmotitsk** [comment]
Fixed.
